### ISSUE TITLE
sanityCheck fails on proxied classes

### ISSUE THREAD

**Issue by clouddistortion** [jensalm/strategy#1]
First of all, great work - really like your approach.

Using AOP I ended up with some problem in the "private void sanityCheck(Collection<Object> annotatedBeanClasses)" method.

If you have a proxied class the following line does not resolve to a bean:
`Strategy strategyAnnotation = AnnotationUtils.findAnnotation(bean.getClass(), Strategy.class);`

I fixed it that way (which might not be the best way but shows a possible solution):

```
Strategy strategyAnnotation = AnnotationUtils.findAnnotation(bean.getClass(), Strategy.class);
if (strategyAnnotation == null){
    try {
        Object target = ((Advised) bean).getTargetSource().getTarget();
        strategyAnnotation = AnnotationUtils.findAnnotation(target.getClass(), Strategy.class);
    } catch (Exception e) {
        log.error("Could not resolve strategyAnnotation for spring bean!", e);
    }
}
```

**Comment by jensalm** [comment]
Thank you. I just incorporated your suggestions.
